services:
  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_schema
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://db:3308/my_schema -schemas=my_schema -user=docker -password=admin -connectRetries=10 migrate
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

