spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_schema
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  docker:
    compose:
      enabled: false
server:
  port: 8080
spring-doc:
  paths-to-match:
    - /auth/**
    - /**
  swagger-ui:
    use-root-path: true
security:
  jwt:
    token:
      secret-key: 25745e
      expire-length: 3600000
